### ISSUE TITLE
Autoclose action messages

### ISSUE THREAD

**Issue by Sundanze** [glewe/teamcal-neo#1]
**What version are you referring to?**
3.9.3

**Is your improvement request related to a problem? Please describe.**
Whenever an action is performed, e.g. saving an object, a success, warning or error message is displayed at the top of the page. I'm always a bit annoyed that I have to manually close them.

![Clipboard_09-06-2024_01](https://github.com/user-attachments/assets/086de407-4590-418c-8173-7dc51d5a442f)

**Describe the solution you'd like**
A timer would be great, e.g. 10 seconds after which the message box closes automatically.

Best regards,
Sundance

**Comment by glewe** [comment]
Makes absolutely sense. Will do so...
