### ISSUE TITLE
Make MFA optional

### ISSUE THREAD

**Issue by lhugensc-hwl** [glewe/teamcal-neo#10]
**What version are you referring to?**
4.0.0

**Is your improvement request related to a problem? Please describe.**
Not a real problem but we want to disable multi-factor authentication on login screen so our users don't use it.

**Describe the solution you'd like**
We want an option to deactivate mfa since we don't want to maintain it on our installation. 
Since it would cause extra workload (e.g. when user lost his phone or something) it should not be possible for users to activate it.

**Comment by glewe** [comment]
Good idea. I will implement that for the next release...

**Comment by glewe** [comment]
Now available in v4.1.1
