### ISSUE TITLE
Dark mode switch

### ISSUE THREAD

**Issue by Sundanze** [glewe/teamcal-neo#2]
**What version are you referring to?**
3.9.3

**Is your feature request related to a problem? Please describe.**
A dark mode theme is available in TeamCal Neo. However, it requires permissions and several clicks for a user to activate it. It also has to reload the current page instead of changing it on the fly.

**Describe the solution you'd like**
Bootstrap offers an on-the-fly switch between dark and light mode. It would be great if that could be integrated in TeamCal Neo.

Best regards,
Sundance

**Comment by glewe** [comment]
Thanks for the suggestion. I was already playing with that and am currently implementing it...
