### ISSUE TITLE
LDAP test config

### ISSUE THREAD

**Issue by Sundanze** [glewe/teamcal-neo#3]
**What version are you referring to?**
3.9.3

**Is your improvement request related to a problem? Please describe.**
I had some problems configuring LDAP authentication. 

**Describe the solution you'd like**
Forumsys offers a free online LDAP test server here:
https://www.forumsys.com/2022/05/10/online-ldap-test-server/
It would be great that if you could use that config as the default in the disdtribution files together with a user from there to test with.

Best regards,
Sundance

**Comment by glewe** [comment]
That's a very good idea. Will do that...
