### ISSUE TITLE
Add client IP to log event entries

### ISSUE THREAD

**Issue by Sundanze** [glewe/teamcal-neo#4]
**What version are you referring to?**
3.9.3

**Is your improvement request related to a problem? Please describe.**
For some users, as for me, it might be helpful to add the client IP address to the log entry when an event is logged.

**Describe the solution you'd like**
Add the client IP address to the event log.

Best regards,
Sundance

**Comment by glewe** [comment]
That is in fact an improvement. I will implement that...
