### ISSUE TITLE
BUG | CKEditor not loading

### ISSUE THREAD

**Issue by Sundanze** [glewe/teamcal-neo#7]
**What version are you referring to?**
4.0.0-beta

**Describe the bug**
On the Framework Configuration page, CKEditor is not loading properly.

**Steps to reproduce**
1. Go to '.Framework Configuraiton'
2. Click on '.Homepage'
3. The editor below 'Welcome Page Text' is not showing
4. Browser console shows some Javascript error

**Comment by glewe** [comment]
I could not reproduce the error. It may have been a browser cache issue on your end.
