### ISSUE TITLE
Test Database on installation page not working

### ISSUE THREAD

**Issue by Sundanze** [glewe/teamcal-neo#8]
**What version are you referring to?**
4.0.0-beta

**Describe the bug**
When installing TeamCal Neo (using installation.php) there is a Test Database button. It returns a conenction error even though I eneterd the correct database credentials.

**Steps to reproduce**
1. Start installation.php
2. Enter correct database details
3. Click on 'Test Database'

**Expected behavior**
"Test Database" return successful

**Actual behavior**
A connection error is returned

**Comment by glewe** [comment]
I improved the database check script. It's more precise now.
