### ISSUE TITLE
Global font not working

### ISSUE THREAD

**Issue by Sundanze** [glewe/teamcal-neo#9]
**What version are you referring to?**
4.0.0

**Describe the bug**
When switching the theme font on the Framework Configuraton page it seems that it is not applied.

**Steps to reproduce**
1. Go to 'Framework Configuration'
2. Select "Theme" tab'
3. Select a different Font and save
4. Font is not changing

**Expected behavior**
The new font is loaded, at least after a nother refresh.

**Actual behavior**
Font is not changing

**Comment by glewe** [comment]
Confirmed. Will be addressed...

**Comment by glewe** [comment]
Until release, here is a manual fix:
https://github.com/glewe/teamcal-neo/commit/4f96d4719550bba376162f7e008c7b6112b220d3

**Comment by glewe** [comment]
Released with 4.1.0
